databases:
  - name: e-design-sharedb
    databaseName: e_design_sharedb
    user: e-design-share
    region: singapore

services:
  - type: web
    name: e-design-share
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: e-design-sharedb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

